//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÇalışLanAMK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArmaganYuzukEntities : DbContext
    {
        public ArmaganYuzukEntities()
            : base("name=ArmaganYuzukEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Satici> Satici { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<Yuzuk> Yuzuk { get; set; }
        public virtual DbSet<SiparisGoruntule> SiparisGoruntule { get; set; }
    }
}
