//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÇalışLanAMK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int satis_id { get; set; }
        public int urun_id { get; set; }
        public int satis_miktar { get; set; }
        public int musteri_id { get; set; }
        public int satici_id { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Satici Satici { get; set; }
        public virtual Yuzuk Yuzuk { get; set; }
    }
}
