//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÇalışLanAMK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yuzuk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yuzuk()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int satici_id { get; set; }
        public string urun_ad { get; set; }
        public int urun_id { get; set; }
        public int stok_adet { get; set; }
        public int fiyat { get; set; }
        public string cins { get; set; }
        public string tas { get; set; }
    
        public virtual Satici Satici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
